---
- name: Import VPC Variables
  include_vars: vars/vpc_vars.yml

- name: Create japp VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: "{{ state }}"
    tenancy: default
    tags: 
      ManagedBy: Ansible
  register: vpcout
    # no_log: true

- debug:
    var: vpcout

- name: Create vpc public subnet in Zone 1
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PubSub1Cidr }}"
    region: "{{ region }}"
    az: "{{ zone1 }}"
    map_public: true
    tags:
      Name: Public Subnet - 1
      ManagedBy: Ansible
  register: pubsub1_out

# - debug:
#     var: subnetzone1_out

- name: Create vpc public subnet in Zone 2
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PubSub2Cidr }}"
    region: "{{ region }}"
    az: "{{ zone2 }}"
    map_public: true
    tags:
      Name: Public Subnet - 2
      ManagedBy: Ansible
  register: pubsub2_out

- name: Create vpc public subnet in Zone 3
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PubSub3Cidr }}"
    region: "{{ region }}"
    az: "{{ zone3 }}"
    map_public: true
    tags:
      Name: Public Subnet - 3
      ManagedBy: Ansible
  register: pubsub3_out

- name: Create vpc private subnet in Zone 1
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PrivSub1Cidr }}"
    region: "{{ region }}"
    az: "{{ zone1 }}"
    tags:
      Name: Private Subnet - 1
      ManagedBy: Ansible
  register: privsub1_out

- name: Create vpc private subnet in Zone 2
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PrivSub2Cidr }}"
    region: "{{ region }}"
    az: "{{ zone2 }}"
    tags:
      Name: Private Subnet - 2
      ManagedBy: Ansible
  register: privsub2_out

- name: Create vpc private subnet in Zone 3
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PrivSub3Cidr }}"
    region: "{{ region }}"
    az: "{{ zone3 }}"
    tags:
      Name: Private Subnet - 3
      ManagedBy: Ansible
  register: privsub3_out