---
- name: Import VPC Variables
  include_vars: vars/vpc_vars.yml

- name: Create japp VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: "{{ state }}"
    tenancy: default
    tags: 
      ManagedBy: Ansible
  register: vpcout
    # no_log: true

- debug:
    var: vpcout

- name: Create vpc public subnet in Zone 1
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpcout.vpc.id }}"
    cidr: "{{ PubSub1Cidr }}"
    map_public: true
    tags:
      Name: Public Subnet - 1
      ManagedBy: Ansible
  register: subnetzone1_out