---
- name: Import VPC Variables
  include_vars: vars/output_vars.yml

- name: Create bation EC2 key
  amazon.aws.ec2_key:
    name: bation-key
    region: "{{region}}"
  register: keyout

- debug:
    var: keyout

- name: Save private key in a file bastion.pem
  copy:
    content: "{{keyout.key.private_key}}"
    dest: ./bation-key.pem
    mode: 0600
  when: keyout.changed

- name: Create Security Group for bastion host
  amazon.aws.ec2_security_group:
    name: "Bation-Host-SG"
    description: Allows port 22 from my IP
    region: "{{region}}"
    vpc_id: "{{vpcid}}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{MYIP}}"
        rule_desc: allow SSH from my IP
    register: BastionSG_out

- debug:
    var: BastionSG_out

- name: Create an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "Bastion-Host"
    vpc_subnet_id: "{{pubsub1id}}"
    instance_type: t2.micro
    security_group: "{{BastionSG_out.group_id}}"
    network_interfaces:
      - assign_public_ip: true
    image_id: "{{bation_ami}}"
    wait: true
    wait_timeout: 400
    tags:
      ManagedBy: Ansible
      Owner: DevOp
    exact_count: 1
  register: bastionHostOut

- debug:
    var: bastionHostOut

- name: Insert/Update "BastionSGid" in vars/output_vars.yml
  blockinfile:
    path: vars/output_vars.yml
    backup: true
    block:
      bastionSGid: "{{bastionHostOut.group_id}}"